#ifndef FLOWMETER_H
#define FLOWMETER_H

#define FLOWMETER_I2C_ADDR_BASE 0x08

#define FLOWMETER1_I2C_ADDR (FLOWMETER_I2C_ADDR_BASE + 0)
#define FLOWMETER2_I2C_ADDR (FLOWMETER_I2C_ADDR_BASE + 1)
#define FLOWMETER3_I2C_ADDR (FLOWMETER_I2C_ADDR_BASE + 2)

#endif
