; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
; OTA upload targets are in default_envs so `pio run -t upload` works
default_envs = rainpump32, raingauge32

[env]
framework = arduino
lib_ldf_mode = chain+
monitor_speed = 115200
test_ignore = test_desktop

[env:flowmeter1]
platform = atmelavr
board = digispark-tiny
build_flags = -DFLOWMETER -DFLOWMETER_OFFSET=0
build_src_filter=+<flowmeter.cpp>

[env:flowmeter2]
platform = atmelavr
board = digispark-tiny
build_flags = -DFLOWMETER -DFLOWMETER_OFFSET=1
build_src_filter=+<flowmeter.cpp>

[env:flowmeter3]
platform = atmelavr
board = digispark-tiny
build_flags = -DFLOWMETER -DFLOWMETER_OFFSET=2
build_src_filter=+<flowmeter.cpp>

[env:flowtester]
platform = espressif8266
board = huzzah
build_flags = -DFLOW_TESTER -DFLOWMETER_OFFSET=0
build_src_filter=+<flowtester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = flowtester.local
;upload_port = 192.168.198.17
upload_flags = --auth=goaway
lib_deps =
	adafruit/Adafruit SH110X@^2.0.0
	adafruit/Adafruit BusIO@^1.7.5
	stevemarple/AsyncDelay@^1.1.2

[env:snitchtester]
platform = espressif8266
board = huzzah
build_flags = -DSNITCH_TESTER
build_src_filter=+<flowtester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = flowtester.local
;upload_port = 192.168.198.17
upload_flags = --auth=goaway
lib_deps =
	adafruit/Adafruit SH110X@^2.0.0
	adafruit/Adafruit BusIO@^1.7.5
	stevemarple/AsyncDelay@^1.1.2

[env:v2tester]
platform = espressif8266
board = huzzah
build_flags = -DV2TESTER
build_src_filter=+<v2tester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = flowtester.local
upload_flags = --auth=goaway
lib_deps =
	https://github.com/cscott/Adafruit-GFX-Library#2f9ccafe311dcb689602d7c7a4a817403bb91663
	;adafruit/Adafruit SH110X@^2.0.0
	;adafruit/Adafruit BusIO@^1.7.5
	stevemarple/AsyncDelay@^1.1.2

[env:v2tester32]
platform = espressif32
board = featheresp32
build_flags = -DV2TESTER32 -DSOFTWARE_SPI
build_src_filter=+<v2tester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
;upload_port = flowtester.local
upload_port = 192.168.198.213
upload_flags = --auth=goaway
lib_deps =
	https://github.com/cscott/Adafruit-GFX-Library#2f9ccafe311dcb689602d7c7a4a817403bb91663
	;adafruit/Adafruit SH110X@^2.0.0
	;adafruit/Adafruit BusIO@^1.7.5
	stevemarple/AsyncDelay@^1.1.2

[env:lcdtester]
platform = espressif8266
board = huzzah
build_flags = -DLCDTESTER
build_src_filter=+<lcdtester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = flowtester.local
upload_flags = --auth=goaway
lib_deps =
	stevemarple/AsyncDelay@^1.1.2

[env:lcdtester32]
platform = espressif32
board = featheresp32
build_flags = -DLCDTESTER32
build_src_filter=+<lcdtester.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
;upload_port = flowtester.local
upload_port = 192.168.198.226
upload_flags = --auth=goaway
lib_deps =
	stevemarple/AsyncDelay@^1.1.2

[env:raingauge32]
platform = espressif32
board = featheresp32
build_flags = -DRAINGAUGE_V2 -DSOFTWARE_SPI
build_src_filter=+<v2rain.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = raingauge.local
;upload_port = 192.168.198.23
upload_flags = --auth=goaway
; was: dawidchyrzynski/home-assistant-integration@^2.0.0
; two different PubSubClients: picked latter arbitrarily
; Library Manager:  - knolleary/PubSubClient@2.8
; Library Manager:  - drk/PubSubClient@2.8
lib_deps =
	adafruit/Adafruit GFX Library@^1.10.14
	bblanchon/ArduinoJson@^6.18.0
	stevemarple/AsyncDelay@^1.1.2
	adafruit/Adafruit ADS1X15@^2.2.0
	https://github.com/cscott/arduino-home-assistant#a04db90fee1ef3d39f2a9a5c9cafad00518e468a
	drk/PubSubClient@2.8

[env:rainpump32]
platform = espressif32
board = featheresp32
build_flags = -DRAINPUMP_V2 -DSOFTWARE_SPI
build_src_filter=+<v2rain.cpp>
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = rainpump.local
;upload_port = 192.168.198.22
upload_flags = --auth=goaway
lib_deps =
	adafruit/Adafruit GFX Library@^1.10.14
	bblanchon/ArduinoJson@^6.18.0
	stevemarple/AsyncDelay@^1.1.2
	adafruit/Adafruit ADS1X15@^2.2.0
	https://github.com/cscott/arduino-home-assistant#a04db90fee1ef3d39f2a9a5c9cafad00518e468a
	drk/PubSubClient@2.8


[env:snitch]
;platform = raspberrypi
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = pico
build_flags = -DSMRTYSNITCH -Wno-ignored-qualifiers
build_src_filter=+<smrtysnitch.cpp>
;upload_protocol = picotool
; THIS DOESN'T WORK AUTOMATICALLY, WE NEED TO MANUALLY BUILD THIS
; using https://wokwi.com/tools/pioasm
;pio_src = src/hello.pio
;lib_deps =
;	stevemarple/AsyncDelay@^1.1.2

; Desktop platform, for library testing
; see https://platformio.org/platforms/native
[env:native]
platform = native
framework =
build_flags = -DNATIVE_BUILD
build_src_filter=+<desktop.c>
test_ignore = test_embedded
